### ISSUE TITLE
Webpack "define cannot be used indirect"

### ISSUE THREAD

**Issue by nbwar** [jonschlinkert/pretty-remarkable#4]
When loaded through webpack you get an error `define cannot be used indirect`.

I traced this down to be a problem with your dependency module `list-item`. 

May have tracked it down to
https://github.com/doowb/set-getter/blob/master/index.js#L29

Are you using `set-getter` in any of the dependencies?

**Comment by jonschlinkert** [comment]
> I traced this down to be a problem with your dependency module list-item.

I've seen this once before. This is a webpack bug. Webpack has a problem with variables named `define`, which is a 100% valid variable name.

**Comment by nbwar** [comment]
Webpack uses `define` as a global function therefore it thinks its calling `amd-module` which is why this error is thrown.  Do you know the author of `set-getter`? It seems to be based of your `set-value` library. 

https://github.com/webpack/webpack/issues/2958

**Comment by jonschlinkert** [comment]
> Do you know the author of set-getter? It seems to be based of your set-value library.

Yes, I'm a collaborator on that package. 

> Webpack uses define as a global function therefore it thinks its calling amd-module which is why this error is thrown

Right, this is a bug in webpack, because it's not calling an amd-module. Browserify doesn't have this issue because it uses node's `require` system, and node's require system doesn't have this issue, but webpack does have this issue. 

I'm curious why you would still want to create an issue on set-getter knowing that this has nothing to do with that library. I suggest you add a comment to that issue on webpack describing the bug to help the maintainers get it fixed. After a [quick search](https://github.com/webpack/webpack/search?q=define&state=open&type=Issues&utf8=%E2%9C%93) of the webpack issues, I found a few other issues related to this as well.

**Comment by nbwar** [comment]
I added an issue there because it is indeed an issue if someone is trying to use that package with webpack. Although it is an issue with webpack, they have had the issue for months and its seems to be a 'nice to have' and 'opinionated' change where a quick fix to get this library working on webpack builds is to change the function name.

**Comment by jonschlinkert** [comment]
> I added an issue there because it is indeed an issue if someone is trying to use that package with webpack.

but you're asking other library maintainers to actually change their code to accommodate a bug in webpack. Please understand that from my perspective it's not a "quickfix" because I can think of at least [78 other packages](https://www.npmjs.com/package/define-property) that would need to be updated as well. Or should we just update those "as you need them"? Hopefully you can see the faulty logic here. This really needs to be fixed in webpack, because even if we were to change the variable names in set-getter, it's just coincidental that it's that library surfacing atm. Tomorrow it might be something else. To fix the problem, we need to "strike at the root" and do it in webpack.

I do understand how you feel though, webpack has a ridiculous number of issues and this might never get resolved. Maybe it's possible to create a transform or plugin to do this.

**Comment by nbwar** [comment]
I just glanced quickly at the package and assumed the define function was an internal function didn't read the docs you are correct. I'll continue to look into better workarounds.
